# Generated by Django 4.0.1 on 2022-01-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='property_images/')),
                ('cost', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('contact_info', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HOUSE', 'house'), ('LAND', 'land'), ('APARTMENT', 'apartment')], max_length=50)),
            ],
        ),
    ]
