# Generated by Django 4.0.1 on 2022-01-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
