# Generated by Django 4.0.1 on 2022-01-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estate.propertytype'),
        ),
    ]
