# Generated by Django 4.0.1 on 2022-01-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HOUSE', 'house'), ('LAND', 'land'), ('APARTMENT', 'apartment')], max_length=50),
        ),
        migrations.DeleteModel(
            name='PropertyType',
        ),
    ]
