# Generated by Django 4.0.1 on 2022-01-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
