# Generated by Django 4.0.1 on 2022-01-12 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='location',
        ),
    ]
